### ISSUE TITLE
Stuck waiting for server

### ISSUE THREAD

**Issue by ibhandal** [ros/actionlib#103]
I wrote a code that should connect to move_base but when I use ac.waitForServer(); The code just waits forever. I know move_base is an action I should be able to connect to because when pulling up rostopic list, it's there. In the picture I use while(!ac.waitForServer()){} but I've also just used ac.waitForServer(); and the same issue arises. I'm coming to believe that it is an issue with my laptop, but everything else that uses ros works. If I delete the part where it waits the robot just moves in circles, without me giving it any directions. getpose just gets a user generated position and gotopose should take that position and move the robot. All of this is running through gazebo.

![screenshot from 2018-04-19 11-38-28](https://user-images.githubusercontent.com/32079293/39011413-369bb50c-43c6-11e8-85d0-20716d828471.png)
 
![screenshot from 2018-04-18 19-21-36](https://user-images.githubusercontent.com/32079293/39011309-edbad624-43c5-11e8-8640-c835c41639ce.png)
![screenshot from 2018-04-18 19-29-00](https://user-images.githubusercontent.com/32079293/39011320-f14c6e7e-43c5-11e8-9be6-b905f469c41d.png)

**Comment by mikaelarguedas** [comment]
Hi @ibhandal,
In case you are not aware of our [support guidelines](http://wiki.ros.org/Support): Please ask your questions on ROS answers and don't post pictures of code as they are not searchable or copy-n-paste able.

Thanks!

I'm going to close this in favor of a ROS Answers question. You can comment here with a link to your ROS answers question for future readers
