### ISSUE TITLE
boost::posix_time::milliseconds does not allow float point value initialization

### ISSUE THREAD

**Issue by victl** [ros/actionlib#104]
With recent release of the Boost Library, boost::posix_time no longer permit initialize a milliseconds/microseconds with a float point value. This broke some of the packages of ROS, and 'actionlib' is one that's been affected. Other packages being affected include 'rostime' and 'laser_assembler'.

I'm opening this issue here hoping someone could fix it for the good of all people.

I encountered this issue when compiling ROS on my macOS box, which has Boost-1.67.0. And I've fixed them manually, but found it tedious to fork & pull request those fixes. If there is indeed a need to do so, I might do it in the future.

**Comment by mikaelarguedas** [comment]
Thanks @victl,

It looks like boost was expecting floating point values before (as it's always explicitely passed floating point values in the code).
Do you know what is the oldest version of boost for which this change will work ?

>  And I've fixed them manually, but found it tedious to fork & pull request those fixes. 

PRs would be much appreciated. If there are repos where this is a one line fix, you can use the github UI to edit the file directly and github will take care of forking the repo for you and allow you to open PRs in one click.
if you don't have time to create PRs, please consider posting your diff on this issue report, that will save time for anyone wanting to pick this up
