### ISSUE TITLE
Using a action's result

### ISSUE THREAD

**Issue by waltejon** [ros/actionlib#121]
Hello together,

together with another student, we have written a action client and server by using `actionlib/client/simple_action_client.h` and `actionlib/server/simple_action_server.h`.

At the terminal we can see the result correctly.

Now we would like to use result for further activities. For this the source file of the client contains:

`actionlib::SimpleActionClient<manipulator::DetectionAction>::ResultConstPtr result = *(ac.getResult())`

`ac` is our action client, `manipulator::DetectionAction` is the `ActionSpecs` from the header file.

We have already started several [attempts](https://answers.ros.org/question/63006/action-client-results/), but still are unsuccessful.

The compiler error is

>`actionlib::SimpleActionClient<manipulator::DetectionAction>::ResultConstPtr` is private.

We would really appreciate, if someone could help us.

Thanks a lot!

**Comment by tfoote** [comment]
Please ask questions on https://answers.ros.org following our support guidelines: https://wiki.ros.org/Support  We use the issue tracker for tracking development of features and resolving bugs.
