### ISSUE TITLE
wait_for_server: is it necessary to require node to be initialised? 

### ISSUE THREAD

**Issue by liborw** [ros/actionlib#16]
When I try to call `wait_for_server` from script not node or from python interpreter the following error is raised:

```
ROSInitException: time is not initialized. Have you called init_node()?
```

The problem is that the wait_for_service uses `rospy.get_rostime()`. Is it necessary, The `wait_for_service` uses `time` and it works perfectly fine?

**Comment by dirk-thomas** [comment]
In order to utilize the communication infrastructure (which `wait_for_server` needs) the ROS node must have been initialized. Please consider asking question on http://answers.ros.org in the future.
