### ISSUE TITLE
wait_for_service(): Race at startup; use wall time

### ISSUE THREAD

**Issue by RainCT** [ros/actionlib#19]
Hi,

wait_for_service() uses the following check for its timeout feature:

> timeout_time = rospy.get_rostime() + timeout

This fails miserably when time is zero (because simulation is being used and it hasn't been initialized yet). It'd probably make more sense to use wall time here.

**Comment by esteve** [comment]
Could you test this branch and let me know if it solves this issue? Thanks

https://github.com/esteve/actionlib/tree/wall-time

**Comment by RainCT** [comment]
Hm, I can't reproduce the problem right now, but the patch looks fine.

I guess there is probably also the same problem with the C++ waitForActionServerToStart (which uses Time::now() vs. WallTime::now()).

**Comment by esteve** [comment]
Thanks for testing my patch. However, I'd rather not merge that branch right now and instead, wait to see if this bug affects other people.

**Comment by beetleskin** [comment]
It does: https://answers.ros.org/question/10290/weird-behavior-when-instantiating-simpleactionclient-right-after-initializing-node-in-rospy/
