### ISSUE TITLE
Actionlib reconnect problem (c++ , with test case)

### ISSUE THREAD

**Issue by cdellin** [ros/actionlib#7]
(See this ROS Answers post [1]).

I'm unable to get my action clients to reconnect to their servers for more than a single request when the connection is temporarily lost (e.g. when the server node is restarted).  I've tried both regular action servers/clients and the simple versions.

I've written a small test case [2] to illustrate the problem.  The client checks isServerConnected every second, and if it is, it sends a goal to the server.  The server rejects every goal it receives.  Leave the client up, and bring the server up and down several times.  After the first server restart and the first goal is sent, isServerConnected always returns false, despite both nodes being up.

I believe this is a bug in the actionlib code.  If anyone can suggest a simpler test case, or any additional methods to help debug the problem, that would be great.  I suppose it could also be a bug in roscpp.

I'm using ROS Groovy on Ubuntu Precise 12.04 (64-bit) with actionlib version 1.9.11-0precise-20130325-2034-+0000.

[1] http://answers.ros.org/question/70012/actionlib-reconnect-problem-c-with-test-case/
[2] http://dellin.net/box/actionlib_cpp_disconnect.tar

**Comment by dirk-thomas** [comment]
I can reproduce the issue. In my case sometimes it works, sometimes it doesn't.

It seems to be timing related. If the deregister of the callback is invoked before registering the new one it works. If it is the other way around the register is basically a no-op and the following deregister will disconnect the server.

**Comment by dirk-thomas** [comment]
Can you please try the patched version from pull request #13 and verify that it fixes your issue?

**Comment by cdellin** [comment]
I was finally able to verify that this diff fixed my issue.  Thanks.
