### ISSUE TITLE
axclient.py crashes with missing module on ROS Kinetic

### ISSUE THREAD

**Issue by airballking** [ros/actionlib#78]
I just ran ```rosrun actionlib axclient.py``` on a system with ROS Kinetic. It crashed giving this error ```No module named wx```. Installing ```python-wxtools``` fixed the issue for me. Maybe there is a missing dependency?

**Comment by mikaelarguedas** [comment]
Hi @airballking, thanks for reporting the issue. Indeed axclient imports wx without declaring a dependency on it. https://github.com/ros/actionlib/pull/79 and https://github.com/ros/rosdistro/pull/15356 should fix it.

**Comment by airballking** [comment]
Hi @mikaelarguedas, thanks for looking into this. :)
